DjangoFive/DjangoFive/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app.views import user_logout
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name = 'index'),
    path('basic_app/', include('basic_app.urls')), 
    path('logout/', views.user_logout, name = 'logout'),
    path('special/', views.special, name = 'special') 
]

DjangoFive/basic_app/urls.py
from django.urls import path, include
from basic_app.views import user_login 
from basic_app import views 

# TEMPLATE URLS  
app_name = 'basic_app' # this is for the html url referencing

urlpatterns = [
    path('register/', views.register, name = 'register'), 
    path('user_login/', views.user_login, name = 'user_login'),

]

DjangoFive/basic_app/models.py
from django.db import models

# import the basic User model from the django framework 
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model): 

    # Relate this model to the default User model, 
        # do NOT inherit the User class directly, may screw up the databse
    user = models.OneToOneField(User, on_delete=models.CASCADE) 

    # additional fields to be added to the model 
    portfolio_site = models.URLField(blank = True) # blank = T means it's an optional field
    # requires pillow 
    profile_pic = models.ImageField(upload_to = 'profile_pic', blank = True) 

    def __str__(self): 
        return self.user.username 


# REMEMBER TO REGISTER YOUR MODEL IN ADMIN.PY! #

DjangoFive/basic_app/forms.py
from django import forms 
from django.contrib.auth.models import User 
from basic_app.models import UserProfileInfo


# Create the registration form.

class UserForm(forms.ModelForm): 
    password = forms.CharField(widget = forms.PasswordInput()) 

    class Meta():
        model = User 
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm): 
    class Meta(): 
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic') 

DjangoFive/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserProfileInfoForm, UserForm
# Create your views here.

# A lot of coding for working with Users and Authorization is in this file 
# Sometimes, want to save information directly to databases 
# Other times, we want to manipulate the data a little bit before saving it
    # set commit = False 
    # helps prevent collision errors 


def index(request):
    return render(request, 'basic_app/index.html') 


def register(request):
    
    registered = False 

    if request.method == "POST":
        user_form = UserForm(data = request.POST) 
        profile_form = UserProfileInfoForm(data = request.POST) 

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save() 
            user.set_password(user.password) # hashes the password 
            user.save() # commit the entry to the database (for fields of the admin User model)

            profile = profile_form.save(commit = False) # do not commit to database yet. 
            profile.user = user # linking this input 

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save() 
            registered = True 

        else: 
            print(user_form.errors, profile_form.errors) # displays the errors made in the forms 
        
    else: 
        user_form = UserForm() 
        profile_form = UserProfileInfoForm() 

    return render(request, 'basic_app/registration.html',
                        {'user_form':user_form,
                        'profile_form':profile_form,
                        'registered':registered})


# For login and logout functions, need a lot of django functionalities 
    # one of the key logic to include is to show "logout" button when logged in, and vice versa 

from django.urls import reverse
from django.contrib.auth.decorators import login_required
    # a decorator that requires a logged in account to access a particular view
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout

def user_login(request): 

    if request.method == 'POST': # if someone has submitted a login request,
        username = request.POST.get('username') # this 'username' comes from the name = 'username' in the html
        password = request.POST.get('password') 

        user = authenticate(username = username, password = password) 
            # Django automatically authenticates that user (no additional code required) 

        if user: 
            if user.is_active: 
                login(request, user) 
                return HttpResponseRedirect(reverse('index')) # after login successful, redirects them back to homepage 
            else: 
                return HttpResponseRedirect('Invalid account/password') 
        
        else: 
            print("Someone tried to login and failed") 
            print("Username:{} and passowrd{}".format(username, password))
            return HttpResponse('Invalid Login') 

    else: 
        return render(request, 'basic_app/login.html', {})

@login_required
def special(request): 
    return HttpResponse("You are logged in") 


@login_required
def user_logout(request): 
    logout(request) 
    return HttpResponseRedirect(reverse('index')) 

DjangoFive/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>  </title>
</head>
<body>
    <nav class = 'navbar navbar-default navbar-static-top'>
        <div class = 'container'>
            <ul class = 'nav navbar-nav'>
                <li><a class = 'navbar-brand' href="{% url 'index' %}"> HOME </a></li>
                <li><a class = 'navbar-link' href="{% url 'admin:index' %}"> Admin </a></li>
                <li><a class = 'navbar-link' href="{% url 'basic_app:register' %}"> Register </a></li>

                {% if user.is_authenticated %} 
                <li><a class = "navbar-link" href="{% url 'logout' %}"> Logout </a></li>
                {% else %} 
                <li><a class = "navbar-link" href="{% url 'basic_app:user_login' %}"> Login </a></li>
                {% endif %} 

            </ul>
        </div>
    </nav>
    <div class = 'container'>
        {% block body_block %}
        {% endblock %}
    </div>

</body>
</html>

DjangoFive/templates/basic_app/index.html
<!-- Template inheritance -->

{% extends 'basic_app/base.html' %}
{% block body_block %}
<div class = 'container'>
    <h1> Django Level Five </h1>

</div>
{% endblock %}

DjangoFive/templates/basic_app/login.html
{% extends 'basic_app/base.html' %} 
{% block body_block %} 

<div class = 'container'>
    <h1> Please Login </h1>
    <form action="{% url 'basic_app:user_login' %}" method = "post">
        {% csrf_token %} 
        <label for="username"> Username: </label>
        <input type="text" name = 'username' placeholder = 'Enter Username'>

        <label for="password"> Password: </label>
        <input type="password" name = "password">

        <input type="submit" value = "Login">

    </form>
</div>

{% endblock %}

DjangoFive/templates/basic_app/registration.html
{% extends 'basic_app/base.html' %}
{% load static %}


{% block body_block %}

<div class = 'container'>
    {% if registered %}
        <h1>Thank you for registering!</h1>
    {% else %}
        <h1>Register Here!</h1>
        <h3>Fill out the form: </h3>
        <form method = 'post' enctype = 'multipart/form-data'>
            {% csrf_token %}
            {{user_form.as_p}} 
            {{profile_form.as_p}} 
            <input type="submit" value = 'Register'>
<!-- user_form and profile_form need to be defined in views.py -->
        </form>
    {% endif %}
{% endblock %}
</div>